version: '3.1'
services:
  cbp2-bot:
    container_name: CBP2-Bot
    image: "node:18"
    working_dir: /workspace/node/cbp2
    restart: always
    env_file:
      - .env 
    volumes:
      - ./:/workspace/node/cbp2
    command: "npm run docker-run"